#!/bin/sh

PROXY_IPV4_API=$(curl -s -4 ip.sb)
PROXY_IPV6_API=$(curl -s -6 ip.sb)
V_IPV4_API=$(curl -s -4 ip.gs)
V_IPV6_API=$(curl -s -6 ip.gs)

echo  "虚拟 IPV4 地址: $(if [[ $V_IPV4_API == $PROXY_IPV4_API ]];then echo "你本机或代理服务器没有虚拟的IPV4地址";else echo "$V_IPV4_API";fi)"
echo  "虚拟 IPV6 地址: $(if [[ $V_IPV6_API == $PROXY_IPV6_API ]];then echo "你本机或代理服务器没有虚拟的IPV6地址";else echo "$V_IPV6_API";fi)"
echo  "真实 IPV4 地址: $(if [[ $PROXY_IPV4_API == '' ]];then echo "你本机或代理服务器没有真实的IPV4地址";else echo "$PROXY_IPV4_API";fi)"
echo  "真实 IPV6 地址: $(if [[ $PROXY_IPV6_API == $PROXY_IPV4_API ]];then echo "你本机或代理服务器没有真实的IPV6地址";elif [[ $PROXY_IPV6_API == '' ]];then echo "你本机或代理服务器没有真实的IPV6地址";else echo "$PROXY_IPV6_API";fi)"

unlink $0