#!/bin/bash

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

# 不能放在/tmp目录下(系统会自动清除/tmp目录下的文件)
bak_default_local_hostsfile='/opt/hosts.bak'
# 远程订阅地址
remote_hostsfile='http://mirrors.itan90.cn/scripts/other/update_hosts/default_hosts'
# 系统默认hosts文件路径
default_local_hostsfile='/etc/hosts'

function main(){
	date=$(echo "$(date +%Y-%m-%d)")
	time=$(echo "$(date +%H:%M)")
	cat ${bak_default_local_hostsfile} > ${default_local_hostsfile}
	echo '' >> ${default_local_hostsfile}
	echo "# [$date $time] update" >> ${default_local_hostsfile}
	curl -s -k ${remote_hostsfile} >> ${default_local_hostsfile}
}

if [[ -f ${bak_default_local_hostsfile} ]];then 
	main
else
	cat ${default_local_hostsfile} > ${bak_default_local_hostsfile}
	main
fi
